### ISSUE TITLE
Moon lang name is probably not the best name you can give to a language nowadays

### ISSUE THREAD

**Issue by ghost** [glampert/moon-lang#1]
Moon lang is cool and stuff but imagine that I tell you that I know a language called Lua, that translates to Moon in english, that also have a counterpart called Moonscript which is a language that translate to Lua script that is called Moon that is also a language that means Lua in portuguese.

Got the ideia?

So do I!

I suggest a name change but a change that reminds the original purpose but that doesn't clash so much with the remaining implementations.

**Comment by glampert** [comment]
@mathausmendel Since the syntax borrows some constructs from Rust and Lua, I also thought about calling it "Rua", but then Portuguese speakers would complain on why I decided to call it "street". Haha.

Anyways, you get the joke, I chose this name to leave it clear it was a lame rip-off `:P`

This is not a project I think people will use for any serious applications (I hope!), so I didn't really give much thought on the name. I don't have any other ideas at the moment, so feel free to shoot a few if you'd like `;)`.

BTW, did not know about this MoonScript.
